# Generated by Django 5.1.4 on 2024-12-30 15:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Detail',
            fields=[
                ('pk_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
