# Generated by Django 5.1.4 on 2024-12-30 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='message',
            field=models.TextField(),
        ),
    ]
