# Generated by Django 5.1.4 on 2025-01-01 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_student_detail_age_alter_student_detail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
