# Generated by Django 5.1.4 on 2025-01-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_alter_student_detail_age_alter_student_detail_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
