# Generated by Django 5.1.4 on 2025-01-01 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
