# Generated by Django 5.1.4 on 2025-01-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
